#!/bin/bash

for a in /home /tmp/.X11-unix\
    /var/run/docker.sock /usr/bin/docker /etc/passwd /etc/group\
    /etc/gshadow /etc/shadow
  do
  mnt_args="${mnt_args} -v ${a}:${a}"
done

exec docker run --rm -ti --name=bionic\
    ${mnt_args} bionic "$@"
